In [2]:
import numpy as np

# Generating one-dimensional (1D) array.

In [3]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Generating two-dimensional (2D) array.

In [5]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Checking the size or dimension of the array.

In [7]:
a.shape

(10,)

In [8]:
b.shape

(3, 3)

# Check the type

In [10]:
type(a)

numpy.ndarray

In [11]:
type(b)

numpy.ndarray

In [12]:
a.dtype

dtype('int32')

In [13]:
b.dtype

dtype('int32')

# Maximum and Minimum values

In [15]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

In [16]:
np.max(a)

9

In [17]:
np.min(a)

0

# Index of maximum and minimum values

In [18]:
a = np.array([4,2,3,13,5,7,14])

In [19]:
max(a)

14

In [20]:
a.max()    # finding maximum value

14

In [21]:
a.argmax() # index of maximum value

6

In [22]:
a.min()  # finding minimum value

2

In [23]:
a.argmin() # index of minimum value

1

# arange

In [24]:
c = np.arange(0,10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
d = np.arange(0,11,2)
d

array([ 0,  2,  4,  6,  8, 10])

In [27]:
e = np.arange(0,101,20)
e

array([  0,  20,  40,  60,  80, 100])

# linspace

In [28]:
x1 = np.linspace(0,20,5)
x1

array([ 0.,  5., 10., 15., 20.])

In [29]:
x2 = np.linspace(0,10,3)

In [30]:
x2

array([ 0.,  5., 10.])

In [31]:
x3 = np.linspace(0,10,50)

In [32]:
x3

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [33]:
x3.shape

(50,)

# reshape

In [34]:
y = np.arange(0,25)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
y.shape

(25,)

In [37]:
y.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
y.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [39]:
y.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

# zeros and ones

In [40]:
np.zeros(3)

array([0., 0., 0.])

In [41]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [44]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
7 * np.ones((3,3))

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

# eye, generating Identity matrix

In [48]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Random Numbers

## randn 

In [49]:
x1 = np.random.randn(3,3)                    # will generate random numbers from normal distribution.
x1

array([[ 1.40257131,  0.90260642, -1.70144446],
       [-2.67769293,  0.97997437,  0.43856593],
       [ 0.50031538,  1.2596911 ,  2.27602933]])

## rand

In [50]:
x2 = np.random.rand(3,3)                          # will generate random numbers between 0 and 1.
x2

array([[0.79990995, 0.63963101, 0.93317547],
       [0.87562395, 0.32485274, 0.6784229 ],
       [0.01303919, 0.21525476, 0.78579451]])

## randint

In [51]:
x3 = np.random.randint(3,8,10)                  # will generate 10 random integers between 3 and 8.
x3

array([7, 6, 4, 5, 4, 3, 5, 5, 3, 3])

# Indexing and Slicing

## Indexing and slicing with 1D array

In [52]:
ar = np.array([4,2,3,13,5,7,14])

In [53]:
ar[3]  # Indexing

13

In [54]:
ar[6]

14

In [55]:
ar[1:4]  # Slicing

array([ 2,  3, 13])

In [56]:
ar[-1]  # Extracting last member of array.

14

In [57]:
ar[-2] # Extracting second last memeber of array

7

In [58]:
ar[1:]  # Slicing from index 1 to end.

array([ 2,  3, 13,  5,  7, 14])

In [59]:
ar[:4]  # slicing upto index 3

array([ 4,  2,  3, 13])

In [60]:
ar[:-1]  # Include everything except the last member of array

array([ 4,  2,  3, 13,  5,  7])

In [ ]:
ar[::-1]  # Reversing or flipping the array

## Indexing of sub-array and sub-matrix from 2D (matrix) array 

In [61]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [62]:
arr[0] # Extracting first row

array([1, 2, 3, 4])

In [63]:
arr[3] # Extracting last row

array([13, 14, 15, 16])

In [64]:
arr[2][1]

10

In [66]:
arr[2,1] # Other method

10

In [67]:
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [68]:
arr[:,3]   # Extracting last column

array([ 4,  8, 12, 16])

In [69]:
arr[:,3].reshape(-1,1)  # Extracting last column vertically

array([[ 4],
       [ 8],
       [12],
       [16]])

In [70]:
arr[:,3:]  # Other way of Extracting last column vertically

array([[ 4],
       [ 8],
       [12],
       [16]])